export const PKG_PREFIX = '@eomts'
export const PKG_NAME = 'eomts'
export const PKG_CAMELCASE_NAME = 'eomts'
export const PKG_CAMELCASE_LOCAL_NAME = 'eomtsLocale'
export const PKG_BRAND_NAME = 'eomts'
